### ISSUE TITLE
Life Time Drops Date Filter Addition

### ISSUE THREAD

**Issue by LastCavalier1943** [DavidArthurCole/EggLedger#13]
Can a filter be added for date before/after for Lifetime Drops?  Similar to what's on Mission Data but for visualization purposes as the filters are spawned from the same process. Thank you, David!!!

**Comment by DavidArthurCole** [comment]
Will be added in the next beta
![image](https://github.com/user-attachments/assets/5c15bfc6-74c2-4209-9dd5-10574bb01fe9)

**Comment by LastCavalier1943** [comment]
Cool, sounds amazing, David! Appreciate it!

**Comment by DavidArthurCole** [comment]
Fixed in latest release.
