### ISSUE TITLE
Issue with Free Select Multi-View Method on the Mission Data tab

### ISSUE THREAD

**Issue by aendyp** [DavidArthurCole/EggLedger#16]
On the 'Mission Data' tab, if you choose Free Select, both selecting and unselecting a mission will add it to selected missions. If you keep selecting and unselecting it, you rack up a number of duplicate selected missions.

**Comment by DavidArthurCole** [comment]
Fixed in [1.6.4](https://github.com/DavidArthurCole/EggLedger/releases/tag/1.6.4) - had a fix in-code for a while but didn't think it was worth pushing by itself.
