### ISSUE TITLE
MacOS version fails without chrome

### ISSUE THREAD

**Issue by pekapa** [DavidArthurCole/EggLedger#5]
I just downloaded the latest version (1.4.5) for MacOS and it raises a fatal error when opening without chrome being installed.

My app.log has the following data:

    time="2024-01-11T07:35:16-03:00" level=error msg="error loading storage.json: open /Users/---/Downloads/EggLedger/internal/storage.json: no such file or directory"
    time="2024-01-11T07:35:19-03:00" level=fatal msg="unable to locate Chrome"`

I do get a popup window asking if I want to install but after pressing "no" it just dies.

**Comment by DavidArthurCole** [comment]
You need Chrome to run Ledger. It is built on top of Lorca - this is true for all versions of it - MK2's, synth's and mine.
