### ISSUE TITLE
Incomplete filter tooltip broken

### ISSUE THREAD

**Issue by daniel-jakob** [DavidArthurCole/EggLedger#7]
https://github.com/DavidArthurCole/EggLedger/blob/ee20994ec2a48a3103056ce5167db78570041ac7/www/index.html#L820-L825

https://github.com/DavidArthurCole/EggLedger/blob/ee20994ec2a48a3103056ce5167db78570041ac7/www/index.html#L893-L898

When hovering over the incomplete filter warning message, the tooltip is displayed beneath the element above it.
![image](https://github.com/DavidArthurCole/EggLedger/assets/14966098/95ecb75a-adc6-468f-8b6d-1959531dc24d)
I tried changing the z-index to 100 and then 9999 (w/ tailwind's `z-100`, etc) to no avail

**Comment by DavidArthurCole** [comment]
Yeah, this is a long-standing issue. It's a result of the DOM there not being flat, and being unable to exit scope of the parent elements. I'll try to see if I can fix this, but I've given it a great deal of class-fuckery in the past to no avail, so no promises...

**Comment by daniel-jakob** [comment]
https://github.com/DavidArthurCole/EggLedger/commit/3b7febb16b34546356fec1082c7a87f356c63d11 seems to have fixed this! Closing.
